Module: SampleModule
Version: 1.0
Description: Sample Module
Pragmas:
  # list of optional module pragmas

DependsOn:

  - Module: OtherModule
    Version: 0.5-WIP

Outputs:

  # Module Exports
  - Export: SampleLiteralOutputValue
    Description: A description
    Value: 123

  - Export: MyFunction
    Description: A description
    Value: !Ref Function

  # Custom Resources
  - CustomResource: TestModule::MyCustomSnsResource
    Description: A custom resource handler
    Handler: ResourceValue

  - CustomResource: TestModule::MyCustomLambdaResource
    Description: Another custom resource handler
    Handler: Function

  # Macros
  - Macro: MyMacro
    Description: My test macro
    Handler: Function

Entries:

  # Cross-module references
  - Import: DemoS3Bucket
    Entries:

      - Parameter: Bucket
        Type: AWS::S3::Bucket
        Allow: Read

  - Import: OtherModule
    Entries:

      - Parameter: ExportValue
        Type: String

      - Parameter: ExportSecret
        Type: Secret
        Description: cross-module import reference
        Scope: "*"

      - Parameter: Bucket
        Type: AWS::S3::Bucket
        Allow: Read

  # Nested Module
  - Module: NestedModule
    Properties:
      ModuleName: SomeModule
      Version: 0.5-WIP
      SourceBucket: !Ref DeploymentBucketName
    Parameters:
      # optional parameters

  - Variable: SourceValueParameter
    Description: Literal value
    Scope: "*"
    Value: This is a literal value

  - Variable: SourceExpressionParameter
    Description: CloudFormation !Ref expression
    Scope: "*"
    Value: !Ref SourceValueParameter

  - Variable: SourceExpressionListParameter
    Description: List of literal values
    Scope: "*"
    Value:
      - !Ref SourceValueParameter
      - !Ref SourceExpressionParameter
      - !Ref SourceResourceParameter
      - literal value

  - Variable: FifthNestedParameter
    Description: Fifth nested parameter
    Type: Secret
    Scope: "*"
    Value: AQICAHjeGw7GlEczkZKnuQaQHVYq...+CXNRhA/rkOSNUThq4ikMnVU2g==

  - Variable: SixthNestedParameter
    Description: Sixth nested parameter
    Scope: "*"
    Type: Secret
    Value: AQICAHjeGw7GlEczkZKnuQaQHVYq...+CXNRhA/rkOSNUThq4ikMnVU2g==
    EncryptionContext:
      Purpose: Security
      "Spe|cial": "Char|acter"

  - Variable: SourceParameterCollection
    Description: Description for collection parameter
    Scope: "*"
    Entries:

      - Variable: FirstSourceValueParameter
        Description: Nested parameter with a literal value
        Scope: "*"
        Value: A nested literal source value

      - Resource: SecondSourceResourceParameter
        Description: CloudFormation Resource
        Scope: "*"
        Type: AWS::SNS::Topic
        Allow: Publish
        Properties:
          DisplayName: !Ref SourceValueParameter

  - Variable: OtherParameterCollection
    Description: Description for collection parameter
    Scope: "*"
    Value: This collection has a value
    Entries:

      - Variable: FirstNestedParameter
        Description: Same name as first nested parameter in sample parameter collection
        Scope: "*"
        Value: Another literal value

  - Resource: SingleResourceParameter
    Description: Second nested parameter
    Type: AWS::SNS::Topic
    Scope: "*"
    Allow: Publish
    Value: "arn:aws:sns:*:*:*"

  - Resource: MultiResourceParameter
    Description: Second nested parameter
    Type: AWS::SNS::Topic
    Scope: "*"
    Allow: Publish
    Value:
      - "arn:aws:sns:*:*:*"
      - "arn:aws:sns:*:*:*:*"

  # Grant permissiont to resource-less AWS services
  - Resource: RekognitionService
    Description: Permissions required for using AWS Rekognition
    Allow:
        - "rekognition:DetectFaces"
        - "rekognition:IndexFaces"
        - "rekognition:SearchFacesByImage"
    Value: "*"
