version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
  build:
    commands:
      - dotnet msbuild ./buildtools/build.proj /p:SignAssembly=false
artifacts:
  files:
    - Deployment/*