Module: SnsSample
Description: A sample module using an SNS topic
Entries:

  - Resource: MyTopic
    Description: An SNS topic used to invoke the function.
    Type: AWS::SNS::Topic
    Allow: Subscribe

  - Function: MyFunction
    Description: This function is invoked by an SNS topic
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: MyTopic
      - Topic: MyTopic
        Filters:
          store:
            - "example_corp"
          event:
            - anything-but: order_cancelled
          customer_interests:
            - rugby
            - football
            - baseball
          price_usd:
            - numeric: [ ">=" , 100 ]
