# MindTouch Î»#
# Copyright (C) 2018 MindTouch, Inc.
# www.mindtouch.com  oss@mindtouch.com
#
# For community documentation and downloads visit mindtouch.com;
# please review the licensing section.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Module: LambdaSharpRegistrar
Version: 0.5-WIP
Description: LambdaSharp Modules and Functions Registrar
Pragmas:
  - no-module-registration

Outputs:

  - CustomResource: LambdaSharp::Register::Module
    Description: Custom resources for registering LambdaSharp modules
    Handler: RegistrationTopic
    Properties:
      Request:
        - Name: ModuleId
          Required: true
        - Name: ModuleName
          Required: true
        - Name: ModuleVersion
          Required: true
      Response:
        - Name: Registration

  - CustomResource: LambdaSharp::Register::Function
    Description: Custom resources for registering LambdaSharp functions
    Handler: RegistrationTopic
    Properties:
      Request:
        - Name: ModuleId
          Required: true
        - Name: FunctionId
          Required: true
        - Name: FunctionName
          Required: true
        - Name: FunctionLogGroupName
          Required: true
        - Name: FunctionMaxMemory
          Required: true
        - Name: FunctionMaxDuration
          Required: true
        - Name: FunctionPlatform
          Required: true
        - Name: FunctionFramework
          Required: true
        - Name: FunctionLanguage
          Required: true
      Response:
        - Name: Registration

  - Export: ErrorReportTopic
    Description: SNS topic for LambdaSharp module errors
    Value: !Ref ErrorReportTopic

  - Export: UsageReportTopic
    Description: SNS topic for LambdaSharp function usage reports
    Value: !Ref UsageReportTopic

Entries:

  # Rollbar Settings
  - Parameter: RollbarReadAccessToken
    Section: Rollbar Settings
    Label: Read Access Token
    Description: Account-level token for read operations
    Type: Secret
    Scope: Register
    Default: ""

  - Parameter: RollbarWriteAccessToken
    Section: Rollbar Settings
    Label: Write Access Token
    Description: Account-level token for write operations
    Type: Secret
    Scope: Register
    Default: ""

  - Parameter: RollbarProjectPrefix
    Section: Rollbar Settings
    Label: Project Prefix
    Description: Optional prefix when creating Rollbar projects
    Scope: Register
    Default: ""

  # Resources
  - Resource: LoggingStreamReference
    Description: Reference to the Kinesis stream used to ingest the function logs
    Value: !Ref Module::LoggingStreamArn
    Type: AWS::Kinesis::Stream
    Allow: Subscribe

  - Resource: RegistrationTopic
    Description: Custom resource topic for registering LambdaSharp modules
    Type: AWS::SNS::Topic
    Allow: Subscribe

  - Resource: ErrorReportTopic
    Description: SNS topic for LambdaSharp module errors
    Scope: ProcessLogEvents
    Type: AWS::SNS::Topic
    Allow: Publish

  - Resource: UsageReportTopic
    Description: SNS topic for LambdaSharp function usage reports
    Scope: ProcessLogEvents
    Type: AWS::SNS::Topic
    Allow: Publish

  - Resource: RegistrationTable
    Description: DynamoDb table for storing function registrations
    Scope: "*"
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH

  # Functions
  - Function: ProcessLogEvents
    Description: Process log events from all LambdaSharp module functions
    Memory: 128
    Timeout: 30
    Pragmas:
        - no-function-registration
    Sources:
      - Kinesis: LoggingStreamReference

  - Function: Register
    Description: Register LambdaSharp modules and functions
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: RegistrationTopic
