Module: Demo
Description: LambdaSharp Demo
Items:

  - Parameter: SlackToken
    Description: Slack verification token
    Scope: SlackCommand
    Default: ""

  - Resource: MessageTable
    Description: DynamoDB table for storing received messages
    Scope: "*"
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  - Variable: NotifyRecorderTopic
    Scope: public
    Description: The topic that the lambda function subscribes to record messages
    Value: !Ref SnsTopic

  - Resource: SnsTopic
    Description: The topic that the lambda function subscribes to record messages
    Type: AWS::SNS::Topic
    Allow: Subscribe

  - Resource: UsagePlan
    Description: Limit usage for REST API
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: DemoUsagePlan
      ApiStages:
        - ApiId: !Ref Module::RestApi
          Stage: !Ref Module::RestApi::Stage
      Description: Sample usage plan for REST API
      Quota:
        Limit: 500
        Period: MONTH

  - Function: RecordMessage
    Description: Record message in a DynamoDB table
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: SnsTopic

  - Function: SlackCommand
    Description: Respond to slack commands
    Memory: 128
    Timeout: 30
    Sources:
      - SlackCommand: /slack
