Module: LambdaSharpSample.SqsSample
Description: A sample module using SQS queues
Items:

  - Resource: MyFirstQueue
    Description: A sample SQS queue
    Type: AWS::SQS::Queue
    Allow: Receive

  - Resource: MySecondQueue
    Description: A sample SQS queue
    Type: AWS::SQS::Queue
    Allow: Receive

  - Function: MyFunction
    Description: This function is invoked by an SQS queue
    Memory: 128
    Timeout: 15
    Sources:
      - Sqs: MyFirstQueue
      - Sqs: MySecondQueue
        BatchSize: 1
