Module: LambdaSharp.Sample.DynamoDB
Description: A sample module using Kinesis streams
Items:

  - Resource: Table
    Scope: "*"
    Description: Description for DynamoDB table
    Type: AWS::DynamoDB::Table
    Allow: Subscribe
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY

  - Function: MyFunction
    Description: This function is invoked by a DynamoDB stream
    Memory: 128
    Timeout: 15
    Sources:
      - DynamoDB: Table
        BatchSize: 15
